# Generated by Django 4.2.20 on 2025-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='link_to_project',
            field=models.URLField(blank=True, null=True),
        ),
    ]
