# Generated by Django 4.2.20 on 2025-03-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPageTag',
        ),
    ]
