# Generated by Django 5.2.15 on 2026-07-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_image_file_alter_blogpage_body_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Landscape mode only; horizontal width between 1000-3000px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
