# Generated by Django 5.2.15 on 2026-07-06 10:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogindexpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading_block', 2), ('paragraph_block', 3), ('image_block', 6), ('image_file_block', 8), ('quote_block', 11), ('embed_block', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a header size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail_footnotes.blocks.RichTextBlockWithFootnotes', (), {'description': 'A rich text paragraph', 'features': ['bold', 'italic', 'footnotes'], 'icon': 'pilcrow', 'template': 'blocks/paragraph_block.html'}), 4: ('wagtail.blocks.URLBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('image', 7), ('caption', 5), ('attribution', 5)]], {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.CharBlock', (), {'blank': True, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('text', 9), ('attribute_name', 10)]], {}), 12: ('wagtail.embeds.blocks.EmbedBlock', (), {'description': 'An embedded video or other media', 'help_text': 'Insert an embed URL', 'icon': 'media', 'preview_template': 'base/preview/static_embed_block.html', 'preview_value': 'https://www.youtube.com/watch?v=mwrGSfiB1Mg', 'template': 'blocks/embed_block.html'})}, verbose_name='Page body'),
        ),
    ]
